### ISSUE TITLE
When training, 'torch.multiprocessing.spawn.ProcessRaisedException' occured.

### ISSUE THREAD

**Issue by calmiLovesAI** [greatlog/SWAHR-HumanPose#11]
My Environment is Ubuntu 18.04LTS, pytorch-1.10, RTX2080Ti, cuda 11.0.

Traceback (most recent call last):
  File "tools/dist_train.py", line 320, in <module>
    main()
  File "tools/dist_train.py", line 115, in main
    args=(ngpus_per_node, args, final_output_dir, tb_log_dir)
  File "/home/lab/.conda/envs/pytorch-1.10/lib/python3.7/site-packages/torch/multiprocessing/spawn.py", line 230, in spawn
    return start_processes(fn, args, nprocs, join, daemon, start_method='spawn')
  File "/home/lab/.conda/envs/pytorch-1.10/lib/python3.7/site-packages/torch/multiprocessing/spawn.py", line 188, in start_processes
    while not context.join():
  File "/home/lab/.conda/envs/pytorch-1.10/lib/python3.7/site-packages/torch/multiprocessing/spawn.py", line 150, in join
    raise ProcessRaisedException(msg, error_index, failed_process.pid)
torch.multiprocessing.spawn.ProcessRaisedException:

-- Process 0 terminated with the following error:
Traceback (most recent call last):
  File "/home/lab/.conda/envs/pytorch-1.10/lib/python3.7/site-packages/torch/multiprocessing/spawn.py", line 59, in _wrap
    fn(i, *args)
  File "/media/hdd/xxy/swahr/tools/dist_train.py", line 161, in main_worker
    rank=args.rank
  File "/home/lab/.conda/envs/pytorch-1.10/lib/python3.7/site-packages/torch/distributed/distributed_c10d.py", line 576, in init_process_group
    store, rank, world_size = next(rendezvous_iterator)
  File "/home/lab/.conda/envs/pytorch-1.10/lib/python3.7/site-packages/torch/distributed/rendezvous.py", line 183, in _tcp_rendezvous_handler
    store = _create_c10d_store(result.hostname, result.port, rank, world_size, timeout)
  File "/home/lab/.conda/envs/pytorch-1.10/lib/python3.7/site-packages/torch/distributed/rendezvous.py", line 158, in _create_c10d_store
    hostname, port, world_size, start_daemon, timeout, multi_tenant=True
RuntimeError: Address already in use

**Comment by calmiLovesAI** [comment]
I have solved the problem by setting a new `dist-url`.
